module.exports = {
  preset: 'jest-expo',
  transform: {
    '^.+\\.[jt]sx?$': 'babel-jest',
  },
  setupFilesAfterEnv: [
    '@testing-library/jest-native/extend-expect',
    './jest.setup.js'
  ],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/android/',
    '/ios/',
  ],
  transformIgnorePatterns: [
    'node_modules/(?!(jest-?react-native',
    '|@react-native(-community)?',
    '|expo(nent)?',
    '|@expo(nent)?/.*',
    '|@expo-google-fonts/.*',
    '|expo-asset',
    '|expo-file-system',
    '|expo-font',
    '|expo-location',
    '|expo-permissions',
    '|expo-secure-store',
    '|@expo/vector-icons',
    '|react-navigation',
    '|@react-navigation/.*',
    '|@unimodules',
    '|unimodules-permissions-interface',
    '|unimodules-barcode-scanner-interface',
    '|unimodules-constants-interface',
    '|unimodules-core',
    '|unimodules-face-detector-interface',
    '|unimodules-file-system-interface',
    '|unimodules-font-interface',
    '|unimodules-image-loader-interface',
    '|unimodules-permissions-interface',
    '|unimodules-sensors-interface',
    '|unimodules-task-manager-interface',
    '|sentry-expo',
    '|native-base',
    '|react-native-svg',
    '|expo-modules-core',
    '|@firebase/firestore',
    '|firebase))',
  ],
  globals: {
    '__DEV__': true
  },
  moduleNameMapper: {
    '\\.svg': '<rootDir>/__mocks__/svgMock.js',
  },
};
